import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        white: "var(--white)",
        black: "var(--black)",
        "base-background": "var(--base-background)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        border: "var(--border)",
        "border-hover": "var(--border-hover)",
        outline: "var(--outline)",
        separator: "var(--separator)",
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        primary: {
          foreground: "var(--primary-foreground)",
          background: "var(--primary-background)"
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
          hover: "var(--secondary-hover)",
        },
        accent: {
          DEFAULT: "var(--accent-background)",
          foreground: "var(--accent-foreground)",
          1: "var(--accent-1)",
          2: "var(--accent-2)",
          3: "var(--accent-3)",
          4: "var(--accent-4)",
          5: "var(--accent-5)",
          6: "var(--accent-6)",
          7: "var(--accent-7)",
          8: "var(--accent-8)",
          9: "var(--accent-9)",
          10: "var(--accent-10)",
          11: "var(--accent-11)",
          12: "var(--accent-12)",
          a1: "var(--accent-a1)",
          a2: "var(--accent-a2)",
          a3: "var(--accent-a3)",
          a4: "var(--accent-a4)",
          a5: "var(--accent-a5)",
          a6: "var(--accent-a6)",
          a7: "var(--accent-a7)",
          a8: "var(--accent-a8)",
          a9: "var(--accent-a9)",
          a10: "var(--accent-a10)",
          a11: "var(--accent-a11)",
          a12: "var(--accent-a12)",
          contrast: "var(--accent-contrast)",
        },
        neutral: {
          1: "var(--neutral-1)",
          2: "var(--neutral-2)",
          3: "var(--neutral-3)",
          4: "var(--neutral-4)",
          5: "var(--neutral-5)",
          6: "var(--neutral-6)",
          7: "var(--neutral-7)",
          8: "var(--neutral-8)",
          9: "var(--neutral-9)",
          10: "var(--neutral-10)",
          11: "var(--neutral-11)",
          12: "var(--neutral-12)",
          a1: "var(--neutral-a1)",
          a2: "var(--neutral-a2)",
          a3: "var(--neutral-a3)",
          a4: "var(--neutral-a4)",
          a5: "var(--neutral-a5)",
          a6: "var(--neutral-a6)",
          a7: "var(--neutral-a7)",
          a8: "var(--neutral-a8)",
          a9: "var(--neutral-a9)",
          a10: "var(--neutral-a10)",
          a11: "var(--neutral-a11)",
          a12: "var(--neutral-a12)",
          contrast: "var(--neutral-contrast)",
        },
      },
      fontFamily: {
        sans: ["var(--family-text)"],
        mono: ["var(--family-code)"],
        text: ["var(--family-text)"],
        heading: ["var(--family-heading)"],
        display: ["var(--family-display)"],
        code: ["var(--family-code)"],
        emphasis: ["var(--family-emphasis)"],
      },
      fontSize: {
        3: "var(--font-size-3)",
        "3-5": "var(--font-size-3-5)",
        4: "var(--font-size-4)",
        "4-5": "var(--font-size-4-5)",
        5: "var(--font-size-5)",
        6: "var(--font-size-6)",
        "7-5": "var(--font-size-7-5)",
        9: "var(--font-size-9)",
        12: "var(--font-size-12)",
        15: "var(--font-size-15)",
        18: "var(--font-size-18)",
        24: "var(--font-size-24)",
        32: "var(--font-size-32)",
      },
      lineHeight: {
        3: "var(--leading-3)",
        4: "var(--leading-4)",
        5: "var(--leading-5)",
        6: "var(--leading-6)",
        7: "var(--leading-7)",
        8: "var(--leading-8)",
        9: "var(--leading-9)",
        10: "var(--leading-10)",
        none: "var(--leading-none)",
      },
      letterSpacing: {
        tighter: "var(--tracking-tighter)",
        tight: "var(--tracking-tight)",
        normal: "var(--tracking-normal)",
        wide: "var(--tracking-wide)",
        wider: "var(--tracking-wider)",
        widest: "var(--tracking-widest)",
      },
      spacing: {
        px: "var(--space-px)",
        "0.5": "var(--space-0-5)",
        1: "var(--space-1)",
        "1.5": "var(--space-1-5)",
        2: "var(--space-2)",
        "2.5": "var(--space-2-5)",
        3: "var(--space-3)",
        "3.5": "var(--space-3-5)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        9: "var(--space-9)",
        10: "var(--space-10)",
        11: "var(--space-11)",
        12: "var(--space-12)",
        14: "var(--space-14)",
        16: "var(--space-16)",
        20: "var(--space-20)",
        24: "var(--space-24)",
        28: "var(--space-28)",
        32: "var(--space-32)",
        36: "var(--space-36)",
        40: "var(--space-40)",
        44: "var(--space-44)",
        48: "var(--space-48)",
        52: "var(--space-52)",
        56: "var(--space-56)",
        60: "var(--space-60)",
        64: "var(--space-64)",
        72: "var(--space-72)",
        80: "var(--space-80)",
        96: "var(--space-96)",
      },
      borderRadius: {
        none: "var(--rounded-none)",
        xs: "var(--rounded-xs)",
        sm: "var(--rounded-sm)",
        md: "var(--rounded-md)",
        lg: "var(--rounded-lg)",
        xl: "var(--rounded-xl)",
        "2xl": "var(--rounded-2xl)",
        "3xl": "var(--rounded-3xl)",
        full: "var(--rounded-full)",
      },
      width: {
        "3xs": "var(--width-3xs)",
        "2xs": "var(--width-2xs)",
        xs: "var(--width-xs)",
        sm: "var(--width-sm)",
        md: "var(--width-md)",
        lg: "var(--width-lg)",
        xl: "var(--width-xl)",
        "2xl": "var(--width-2xl)",
        "3xl": "var(--width-3xl)",
        "4xl": "var(--width-4xl)",
        "5xl": "var(--width-5xl)",
        "6xl": "var(--width-6xl)",
        "7xl": "var(--width-7xl)",
        body: "var(--width-body)",
      },
      maxWidth: {
        "3xs": "var(--width-3xs)",
        "2xs": "var(--width-2xs)",
        xs: "var(--width-xs)",
        sm: "var(--width-sm)",
        md: "var(--width-md)",
        lg: "var(--width-lg)",
        xl: "var(--width-xl)",
        "2xl": "var(--width-2xl)",
        "3xl": "var(--width-3xl)",
        "4xl": "var(--width-4xl)",
        "5xl": "var(--width-5xl)",
        "6xl": "var(--width-6xl)",
        "7xl": "var(--width-7xl)",
        body: "var(--width-body)",
      },
    },
  },
  plugins: [],
} satisfies Config;
